[package]
name = "notebook-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nb"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
uuid = { version = "1.8.0", features = ["v4"] }
